theme: jekyll-theme-slate
title: ModRev - Model Revision tool for Boolean logical models of biological regulatory networks
ddescription: Model Revision tool to repair Boolean logical models of biological regulatory networks
